[build]
  publish = "./public"
  command = "./src/deno/netlify.sh"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'; connect-src 'self'; img-src 'self' data:; script-src 'self' 'sha256-6nprweej8TYdNiCe7TPmwEzG0aayYxulGBCaDeQKGG8='; style-src 'self' 'sha256-Kn8FBM+r1oeoKdlvISkM2KmklJjaAO6ehN2F4zEo1e0=' 'sha256-p0lVhHvjWu1bucdPJXr5SjN6e3hVy6Jv4paG9r+Nsbc=';"
    Referrer-Policy = "same-origin"
    Permissions-Policy = "interest-cohort=()"
