import * as fs from 'fs';
import * as path from 'path';
import * as base64 from 'base64';
import * as esbuild from 'esbuild';
import * as css from './css.ts';
import * as svelte from './svelte.ts';
import * as sitemap from './sitemap.ts';
import * as rss from './rss.ts';
import {generateManifest} from './manifest.ts';
import {Props} from './types.ts';

const pwd = path.dirname(new URL(import.meta.url).pathname);
export const buildDir = path.resolve(pwd, `../../public`);
export const cacheDir = path.resolve(pwd, `../.cache`);

// Prep directories
await fs.ensureDir(buildDir);
await fs.ensureDir(cacheDir);
const staticPaths = ['assets', 'images', 'manifest.webmanifest', 'robots.txt'];
for await (const dirEntry of Deno.readDir(buildDir)) {
  if (staticPaths.includes(dirEntry.name)) {
    continue;
  }
  await Deno.remove(path.join(buildDir, dirEntry.name), {recursive: true});
}

export const MANIFEST = await generateManifest(cacheDir);

console.log(`🖨️ ${MANIFEST.meta.generator}`);

await css.process(buildDir);

const template = await Deno.readTextFile(
  path.resolve(pwd, `../templates/index.html`)
);

// Retrieve <head> inline CSS
const cssData = await Deno.readTextFile(
  path.join(buildDir, `./assets/css/main.min.css`)
);
const cssHash = await Deno.readTextFile(
  path.join(buildDir, `assets/css/main.min.txt`)
);

// Retrieve <head> inline JavaScript
const headData = await Deno.readTextFile(
  path.resolve(pwd, `../templates/head.min.js`)
).then(
  (data) =>
    `;window.dbushell={version: '${MANIFEST.meta.version}'};${data.trim()}`
);
const headHash = base64.encode(
  new Uint8Array(
    await crypto.subtle.digest('sha-256', new TextEncoder().encode(headData))
  )
);

export const renderRoute = async (props: Props, bypassCache = false) => {
  // TODO: better way to define globals?
  const Container = await svelte.ssrComponent(
    props.container,
    {
      define: {
        'globalThis.dbushell': JSON.stringify({
          version: MANIFEST.meta.version
        })
      }
    },
    bypassCache
  );
  const {html: render} = Container.render({
    ...props,
    latest: MANIFEST.latest
  });
  let title = MANIFEST.meta.title;
  let description = title;
  if (props.title) {
    title = `${props.title} – ${title}`;
  }
  if (props.description) {
    description = props.description;
  }
  let html = template;
  html = html.replace(/{{generator}}/, MANIFEST.meta.generator);
  html = html.replace(/{{cssHash}}/, cssHash);
  html = html.replace(/{{cssData}}/, cssData);
  html = html.replace(/{{headHash}}/, headHash);
  html = html.replace(/{{headData}}/, headData);
  html = html.replace(/{{title}}/g, title);
  html = html.replace(/{{description}}/g, description);
  html = html.replace(/{{version}}/g, MANIFEST.meta.version);
  html = html.replace(/{{href}}/g, props.href);
  html = html.replace(/{{render}}/g, render);

  const buildPath = path.join(buildDir, `${props.href}/index.html`);
  await fs.ensureFile(buildPath);
  await Deno.writeTextFile(buildPath, html);
};

console.log(`✧ Rendering routes`);

const renders: Promise<void>[] = [];
for (const [, props] of Object.entries(MANIFEST.routes)) {
  renders.push(renderRoute(props));
}

const tasks: Promise<unknown>[] = [];

tasks.push(
  Promise.all(renders).then(() => {
    console.log(`★ Published ${Object.keys(MANIFEST.routes).length} routes`);
  })
);

// Generate RSS feed
tasks.push(rss.publish(buildDir, MANIFEST));

// Generate Sitemap
tasks.push(sitemap.publish(buildDir, MANIFEST));

// Copy server worker
tasks.push(
  (async () => {
    let sw = await Deno.readTextFile(path.resolve(pwd, `../templates/sw.js`));
    sw = sw.replace(/{{version}}/g, MANIFEST.meta.version);
    sw = `// This file is automatically generated - edit the template!\n${sw}`;
    await Deno.writeTextFile(path.join(buildDir, `sw.js`), sw);
    console.log(`★ Published service worker`);
  })()
);

// Update content security policy headers
tasks.push(
  (async () => {
    const headersPath = path.resolve(pwd, `../templates/_headers`);
    let toml = await Deno.readTextFile(headersPath);
    toml = toml.replace(
      /script-src 'self' 'sha256-[^']+?'/g,
      `script-src 'self' 'sha256-${headHash}'`
    );
    toml = toml.replace(
      /style-src 'self' 'sha256-[^']+?'/g,
      `style-src 'self' 'sha256-${cssHash}'`
    );
    Deno.writeTextFile(path.join(buildDir, `_headers`), toml).then(() => {
      console.log(`★ Updated headers`);
    });
  })()
);

tasks.push(svelte.bundle(buildDir));

await Promise.all(tasks);

// Move 404 template
await Deno.rename(
  path.join(buildDir, `404/index.html`),
  path.join(buildDir, `404.html`)
);

// Tidy up ...
await Deno.remove(path.join(buildDir, `404`), {recursive: true});

esbuild.stop();

console.log(`✹ Built in ${Math.round(performance.now())}ms`);
